openapi: 3.0.0
info:
  title: Catálogo API
  version: 1.0.0
  description: API para gerenciamento de produtos e categorias

servers:
  - url: http://localhost:8082
    description: Servidor de desenvolvimento

paths:
  /produtos:
    get:
      summary: Listar todos os produtos
      tags:
        - Produtos
      responses:
        '200':
          description: Lista de produtos
          content:
            application/json:    
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Produto'
    post:
      summary: Criar um novo produto
      tags:
        - Produtos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProdutoInput'
      responses:
        '201':
          description: Produto criado
          content:
            application/json:    
              schema:
                $ref: '#/components/schemas/Produto'
        '400':
          description: Dados inválidos

  /produtos/{id}:
    get:
      summary: Obter um produto específico
      tags:
        - Produtos
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalhes do produto
          content:
            application/json:    
              schema:
                $ref: '#/components/schemas/Produto'
        '404':
          description: Produto não encontrado
    put:
      summary: Atualizar um produto
      tags:
        - Produtos
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProdutoInput'
      responses:
        '200':
          description: Produto atualizado
          content:
            application/json:    
              schema:
                $ref: '#/components/schemas/Produto'
        '400':
          description: Dados inválidos
        '404':
          description: Produto não encontrado
    delete:
      summary: Excluir um produto
      tags:
        - Produtos
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Produto excluído
        '404':
          description: Produto não encontrado

  /categorias:
    get:
      summary: Listar todas as categorias
      tags:
        - Categorias
      responses:
        '200':
          description: Lista de categorias
          content:
            application/json:    
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Categoria'
    post:
      summary: Criar uma nova categoria
      tags:
        - Categorias
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoriaInput'
      responses:
        '201':
          description: Categoria criada
          content:
            application/json:    
              schema:
                $ref: '#/components/schemas/Categoria'
        '400':
          description: Dados inválidos

  /categorias/{id}:
    get:
      summary: Obter uma categoria específica
      tags:
        - Categorias
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalhes da categoria
          content:
            application/json:    
              schema:
                $ref: '#/components/schemas/Categoria'
        '404':
          description: Categoria não encontrada
    put:
      summary: Atualizar uma categoria
      tags:
        - Categorias
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoriaInput'
      responses:
        '200':
          description: Categoria atualizada
          content:
            application/json:    
              schema:
                $ref: '#/components/schemas/Categoria'
        '400':
          description: Dados inválidos
        '404':
          description: Categoria não encontrada
    delete:
      summary: Excluir uma categoria
      tags:
        - Categorias
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Categoria excluída
        '404':
          description: Categoria não encontrada

components:
  schemas:
    Produto:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        descricao:
          type: string
        preco:
          type: number
        categoria_id:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    ProdutoInput:
      type: object
      required:
        - nome
        - preco
        - categoria_id
      properties:
        nome:
          type: string
        descricao:
          type: string
        imagem:
          type: string
        preco:
          type: number
        categoria_id:
          type: integer

    Categoria:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        descricao:
          type: string
        imagem:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    CategoriaInput:
      type: object
      required:
        - nome
      properties:
        nome:
          type: string
        descricao:
          type: string
        imagem:
          type: string